### ISSUE TITLE
return 400 error while creating contact

### ISSUE THREAD

**Issue by esankhanusiya** [mailchimp/Mailchimp-SDK-Android#17]
val user = auth.currentUser
        val newContact = Contact.Builder(user?.email!!)
            .setContactStatus(ContactStatus.SUBSCRIBED)
            .build()
        val sdk = Mailchimp.sharedInstance()
        sdk.createOrUpdateContact(newContact)

I am trying to creating contact using sdk in android but it always return with 

400 Bad Request https://us20.api.mailchimp.com/clientapi/1.0/contacts

{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Bad Request","status":400,"detail":"User does not exist.","instance":"e3d6f848-8d24-4f68-bc61-e4c4d2e505c7"}

I have set mailchimp configuration in Application class.

**Comment by michael-heard-mc** [comment]
Hi, looks like you might be having an issue with your SDK Key. Can you email us at mobile-sdk@mailchimp.com with your Mailchimp account username? We can then take a closer look.
