### ISSUE TITLE
[BUG] Please enter a short issue title here...

### ISSUE THREAD

**Issue by bdan9559** [mailchimp/Mailchimp-SDK-Android#28]
**Describe the bug**

**To Reproduce**
1) Do this...
2) Do that...
3) See the issue...

**Expected behavior**

**Screenshots**

**Development Environment Information:**
 - Android Studio Version: [e.g. 4.0]
 - Mailchimp SDK Version: [e.g. 1.0]

**build.gradle contents**
Please paste the contents of your `build.gradle` below. Please redact any private information.

**Additional context**

**Comment by charlie-mcknight** [comment]
Hey @bdan9559,
Thanks for filing a bug report. It looks like your description of the bug didn't come through. Would you mind giving us a few more details about the bug you are encountering or closing the issue if it was opened by accident?
