### ISSUE TITLE
[Feature] Ability to send the device language to Mailchimp

### ISSUE THREAD

**Issue by rmtmckenzie** [mailchimp/Mailchimp-SDK-Android#29]
**Is your feature request related to a problem? Please describe.**
I'm using the mobile device sdk to update my audience tags so that I can segment my audience. I'd also like to send up the language so that my email campaigns can be sent in the right languages.

**Describe the solution you'd like**
It'd be great if it were possible to send up the device language (or optionally the app-specific language) through the mobile SDK.

**Describe alternatives you've considered**
I could set up a server instance which would use the marketing API, but this means a fair amount of overhead for something that seems like it could easily be supported.

**Additional context**
N/A

**Comment by michael-patzer** [comment]
@rmtmckenzie Could you use `Locale.current.languageCode` and send it as a tag, so that each user is then tagged with their languageCode? My initial thought is to allow our customers to define this so they can use the language code, or the localized language name, or some other identifier depending on their personal preferences, rather than Mailchimp being prescriptive.

**Comment by rmtmckenzie** [comment]
@michael-patzer Oh hmm I think I was missing something. So if I'm reading the docs correctly now, I can set up an entry in `Audience fields and *|MERGE|* tags` called "LANGUAGE" and then use that in the mail templates the same way I'm currently using `*|IF:MC_LANGUAGE=pt|*` but with `IF:LANGUAGE=` instead? And I set that mergeField when I create the contact from the SDK?

The only annoying thing is if a user were set up using a browser, the MC_LANGUAGE might be set while I'd have to make sure that the LANGUAGE were set myself, but I can definitely live with that.

**Comment by michael-patzer** [comment]
@rmtmckenzie Yes, that's the best way to do what you need now. We'd like to add support for `MC_LANGUAGE` to the SDK, but we don't have an estimate on when that might be released.
