### ISSUE TITLE
[BUG] createOrUpdateContact doesn't work

### ISSUE THREAD

**Issue by zjamshidi** [mailchimp/Mailchimp-SDK-Android#32]
**Describe the bug**
When calling createOrUpdateContact API I get "Bad Request" error. Here is the complete response:

`{"type":"https://mailchimp.com/developer/marketing/docs/errors/","title":"Bad Request","status":400,"detail":"User does not exist.","instance":"d7a5c5aa-4bec-2f2e-8e74-64fdc95ae896"}`

**Expected behavior**
"If you attempt to create a contact that already exists, the contact’s information will be updated with the newly specified values."
So it should create or update the contact.

**Development Environment Information:**
 - Android Studio Version: Chipmunk | 2021.2.1 Patch 1
 - Mailchimp SDK Version: 1.0.0

**Comment by zjamshidi** [comment]
I should have used **Mobile SDK Client keys**

> Go to the[ Your API Keys](https://us1.admin.mailchimp.com/account/api/) section of your Mailchimp account and scroll down to Your Mobile SDK Client keys.

REF: https://mailchimp.com/developer/marketing/docs/mobile-sdk/#mobile-sdk-keys

**Comment by zjamshidi** [comment]
Please provide more information:
 Which SDK are you using?
 What's the error?
 Are you using the proper key?

**Comment by BinjalGori** [comment]
I used your dependency provided 1.1.0 but it didn't work when I did sync
now it gives me error

**Comment by BinjalGori** [comment]
Okay I used this as well but in the mailchimp dashboard the contact doesnot
gets created can you suggest what problem must  be??

**Comment by zjamshidi** [comment]
Please share your code. If you get any error, please share the error as well.

**Comment by BinjalGori** [comment]
Actually not showing any error I get the response while printing the logs
but the contact doesnot gets saved on the dashboard of the MailChimp. Do
you have any idea why this is happening?

**Comment by charlie-mcknight** [comment]
Hey @BinjalGori. I work at Mailchimp on the Eng team. Sharing your code would certainly help us figure out whats going on here. Something else that might help is when you initialize the SDK, turn on debugging to see if we can get any logs. You can see an example of doing that below.

` val configuration = MailchimpSdkConfiguration.Builder(context, sdkKey)
        .isDebugModeEnabled(true)
        .isAutoTaggingEnabled(true)
        .build()
    val mailchimpSdk = Mailchimp.initialize(configuration)`

Also thank you @zjamshidi for helping out!

**Comment by charlie-mcknight** [comment]
Also, @BinjalGori I should point out if you share your code, make sure to **Not** include the sdk key

**Comment by BinjalGori** [comment]
Yes here I my code

fun configuration()
    {
        val configuration: MailchimpSdkConfiguration = Builder(context,
"7fb3a525c9263da65b1ba06a39e91bb9-us12")
            .isDebugModeEnabled(isDebugBuild)
            .isAutoTaggingEnabled(true)
            .build()

        println("mailchimp configuration is: $configuration")

        //working with not null

        //working with not null
        Mailchimp.initialize(configuration)
        println("mailchimp mailchimpSdk is: " +
Mailchimp.initialize(configuration))

    }
    fun mailChimpContact(EMAIL_ADDRESS: String) {
        Global.shared.isMailchimpContect = true
        val isValidEmail =
android.util.Patterns.EMAIL_ADDRESS.matcher(EMAIL_ADDRESS).matches()
        if (!isValidEmail) {
            // Handle invalid email address
            println("Invalid email address format: $EMAIL_ADDRESS")
            return
        }

        // Create a contact
        val contact = Contact.Builder(EMAIL_ADDRESS)
            .setMergeField("mobile", "signup")
            .setContactStatus(ContactStatus.SUBSCRIBED)
            .addTag("mobile-signup")
// .setMarketingPermission(advertisingPermissionKey,true)
            .build()

        println("mailchimp contact is: $contact")

        // Create or update the contact
        val sdk = Mailchimp.sharedInstance()
        sdk.createOrUpdateContact(contact)
        println("contact sdk $contact")
// Mailchimp.sharedInstance().createOrUpdateContact(contact)

        println("mailchimp contactsdk createOrUpdate")


    }
Also the response what I get but the issue is with it is not creating
contact on the MailChimp dashboard

***@***.***,
mergeFields=[MergeField(key=mobile,
value=StringMergeFieldValue(value=signup))], tags=[Tag(name=mobile-signup,
status=active)], marketingPermissions=null, contactStatus=SUBSCRIBED)

**Comment by BinjalGori** [comment]
@zjamshidi @charlie-mcknight here is the code which i have used
fun configuration()
    {
        val configuration: MailchimpSdkConfiguration = Builder(context,
sdkkey)
            .isDebugModeEnabled(isDebugBuild)
            .isAutoTaggingEnabled(true)
            .build()

        println("mailchimp configuration is: $configuration")

        //working with not null

        //working with not null
        Mailchimp.initialize(configuration)
        println("mailchimp mailchimpSdk is: " +
Mailchimp.initialize(configuration))

    }
    fun mailChimpContact(EMAIL_ADDRESS: String) {
        Global.shared.isMailchimpContect = true
        val isValidEmail =
android.util.Patterns.EMAIL_ADDRESS.matcher(EMAIL_ADDRESS).matches()
        if (!isValidEmail) {
            // Handle invalid email address
            println("Invalid email address format: $EMAIL_ADDRESS")
            return
        }

        // Create a contact
        val contact = Contact.Builder(EMAIL_ADDRESS)
            .setMergeField("mobile", "signup")
            .setContactStatus(ContactStatus.SUBSCRIBED)
            .addTag("mobile-signup")
// .setMarketingPermission(advertisingPermissionKey,true)
            .build()

        println("mailchimp contact is: $contact")

        // Create or update the contact
        val sdk = Mailchimp.sharedInstance()
        sdk.createOrUpdateContact(contact)
        println("contact sdk $contact")
// Mailchimp.sharedInstance().createOrUpdateContact(contact)

        println("mailchimp contactsdk createOrUpdate")


    }
Also the response what I get but the issue is with it is not creating
contact on the MailChimp dashboard

mergeFields=[MergeField(key=mobile,
value=StringMergeFieldValue(value=signup))], tags=[Tag(name=mobile-signup,
status=active)], marketingPermissions=null, contactStatus=SUBSCRIBED)

**Comment by charlie-mcknight** [comment]
Thanks for sharing that @BinjalGori. I think we have figured out what is going on. It looks like the email address you are trying to add is being flagged as invalid by our backend. Can you double check that it is a valid email Address?

As for why you aren't getting the logs, double check that you are in fact deploying a debug build. Alternatively, you can just temporarily set your configuration to always output logs like so `.isDebugModeEnabled(true)`. Just make sure to set it back before you distribute your app.

Also it looks like you may have accidentally posted your API key in an earlier revision of your comment. Out of an an abundance of caution, we went ahead and disabled it. You can generate a new key in the same way that you did before. Just make sure to create it in the section entitled "Your Mobile SDK Client keys".

I hope that helps!
- Charlie

**Comment by BinjalGori** [comment]
hello @charlie-mcknight here .isDebugModeEnabled(true)  here i get the logs while running the app but contact doesn't gets created on the dashboard of MailChimp.

This are the logs i get while running the app can you check and help out here 

mailchimp contact is: contact(emailaddress=rajvi.patel@mobiboxsoftech.com, mergeFields=[MergeField(key=mobile, value=StringMergeFieldValue(value=signup))], tags=[Tag(name=mobile-signup, status=active)], marketingPermissions=[MarketingPermission(id=023cda05ec6a930c663625f774c998c7, enabled=true)], contactStatus=SUBSCRIBED)

**Comment by BinjalGori** [comment]
hello @charlie-mcknight here i have used the as .isDebugModeEnabled(true) and also tried with the other email id but still the contact doesnot gets created on the dashboard i get the logs while running the app will show you here can you check and help out here 

mailchimp contact is: contact(emailaddress=rajvi.patel@gmail.com, mergeFields=[MergeField(key=mobile, value=StringMergeFieldValue(value=signup))], tags=[Tag(name=mobile-signup, status=active)], contactStatus=SUBSCRIBED)

**Comment by charlie-mcknight** [comment]
@BinjalGori Thanks for getting back to me. Are you sure you aren't seeing any more logs? You should be seeing logs similar to the following with debugging mode enabled.

```
SDK initialized
…
starting to perform work
…
Creating or updating user was successful for <EMAIL_ADDRESS>
...
finished work with result of SUCCESS
...
Worker result SUCCESS for Work [ id=4c1e96b9-c642-462f-9f6b-0d58a6b6e274, tags={ com.mailchimp.sdk.audience.AudienceWorker } ]
```

Also it looks like you have been able to add contacts in the past using the Mobile SDK. Is this true? Was that on iOS?

I'd also suggest contacting Mailchimp Support directly. They'll be able to give more in depth support into you account.
https://mailchimp.com/help/mailchimp-support-options/
